### PR TITLE
Revert "Hide templates (keboola-ecommerce-shopify, keboola-ecommerce-shoptet)"

### PR DESCRIPTION
**Pull request by MonikaFeigler**
lets revert the last commit, new pull request with fixes is ready

### CODE REVIEW

**Comment by MonikaFeigler** [comment]
@webrouse please, revert it, the new pull request is ready as well.

**Comment by webrouse** [comment]
hi @MonikaFeigler, please add here, to the this PR also the fix, thank you.
it doesn't make sense to revert it without fixing.

**Comment by webrouse** [comment]
(or add revert to the https://github.com/keboola/keboola-as-code-templates/pull/17#event-6704696015)

```
git cherry-pick 40f1e3d
```

**Comment by webrouse** [comment]
Note: It should be in one PR to make change atomic (we have to learn to work this way for the future, when it will be in the production).

**Comment by MonikaFeigler** [comment]
sorry, I'll change it. and commit the new changes here. Just a sec :-) @webrouse

**Review by webrouse — APPROVED** [review]

**Pull request merged**
