### PR TITLE
including updated from beta

### PR DESCRIPTION
**Pull request by MonikaFeigler**

### CODE REVIEW

**Comment by MonikaFeigler** [comment]
@JakubMatejka please, review it so it can go live. Thanks.

**Review by JakubMatejka — APPROVED** [review]
ok. (BTW. no need to mention me again, GitHub sends a notification once you request the review.)

**Comment by MonikaFeigler** [comment]
@JakubMatejka I need 2 approving reviews, who should I ask next when Michal is not available, please?

**Comment by JakubMatejka** [comment]
I changed the rule so that one review is enough now. 🙂

**Pull request merged**
