### PR TITLE
MAIN: breaking changes

### PR DESCRIPTION
**Pull request by MonikaFeigler**
1. support of native types
2. bing ads new component
3. delete of small templates, replaced by complex templates
4. other small changes: renaming in meta.jsonnet

### CODE REVIEW

**Comment by MonikaFeigler** [comment]
TESTS:

**ASANA - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46155750

**PIPEDRIVE - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46157530

**SALESFORCE - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46158926

**Google Analytics - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46162722

**Advertising Platforms - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46164146

**JIRA - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46164965

**Typeform - success**
https://connection.north-europe.azure.keboola.com/admin/projects/8780/queue/46166152

**Comment by MonikaFeigler** [comment]
@ujovlado can you add your approval, please?

**Comment by ujovlado** [comment]
Spravim tam este rebase.

**Comment by ujovlado** [comment]
> Spravim tam este rebase.

Tak nie, su tam konflikty, prizmurim oci :)

**Comment by ujovlado** [comment]
@MonikaFeigler je to rebasnute:

diff neukazuje zmeny:

```
git diff 3c9b305 d270255
```

**Review by ujovlado — APPROVED** [review]

**Pull request merged**
