### PR TITLE
MAIN Typeform Release

### PR DESCRIPTION
**Pull request by MonikaFeigler**

### CODE REVIEW

**Comment by MonikaFeigler** [comment]
It's not ready YET.

**Review by baullmear — COMMENTED** [review]
https://connection.keboola.com/admin/projects/9390/queue/945907886
https://connection.keboola.com/admin/projects/9390/queue/945907669
https://connection.keboola.com/admin/projects/9390/queue/945907299
https://connection.keboola.com/admin/projects/9390/queue/945907039

**Review by baullmear — APPROVED** [review]

**Comment by MonikaFeigler** [comment]
@baullmear ještě jednou prosím :-)

**Review by baullmear — APPROVED** [review]

**Comment by MonikaFeigler** [comment]
before merge, I have to finish documentation.

**Pull request merged**
