### PR TITLE
BETA: GA3, GA4 templates / twitter deletion from templates / datahub update

### PR DESCRIPTION
**Pull request by MonikaFeigler**
Changes:
1. Google analytics template renamed to Universal analytics
2. new template for GA4
3. dathub template update  - sql fix
4. twitter deletion from a template because of deprecated component
5. Thoughtspot hubspot fixes - new columns added into the model

### CODE REVIEW

**Comment by MonikaFeigler** [comment]
@TomNett please approve and merge :-)

**Comment by MonikaFeigler** [comment]
@padak can you please approve those template's changes please? 
Tomis is off. Thank you.

**Comment by padak** [comment]
Go :)

**Review by TomNett — COMMENTED** [review]
OK

**Comment by MonikaFeigler** [comment]
@TomNett prosím approve

**Review by TomNett — APPROVED** [review]
ok!

**Pull request merged**
